# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../FablikFramework/forms/departments/form.ui'
#
# Created: Sat Jan 22 20:10:18 2011
#      by: PyQt4 UI code generator 4.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_departments(object):
    def setupUi(self, departments):
        departments.setObjectName(_fromUtf8("departments"))
        departments.resize(590, 640)
        departments.setMinimumSize(QtCore.QSize(0, 500))
        self.verticalLayout_2 = QtGui.QVBoxLayout(departments)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.newDepBtn = QtGui.QPushButton(departments)
        self.newDepBtn.setObjectName(_fromUtf8("newDepBtn"))
        self.horizontalLayout.addWidget(self.newDepBtn)
        self.newSubDepBtn = QtGui.QPushButton(departments)
        self.newSubDepBtn.setObjectName(_fromUtf8("newSubDepBtn"))
        self.horizontalLayout.addWidget(self.newSubDepBtn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.remDepBtn = QtGui.QPushButton(departments)
        self.remDepBtn.setObjectName(_fromUtf8("remDepBtn"))
        self.horizontalLayout.addWidget(self.remDepBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.departmentsTree = QtGui.QTreeWidget(departments)
        self.departmentsTree.setObjectName(_fromUtf8("departmentsTree"))
        self.verticalLayout.addWidget(self.departmentsTree)
        self.groupBox = QtGui.QGroupBox(departments)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.allRolesList = QtGui.QListWidget(self.groupBox)
        self.allRolesList.setObjectName(_fromUtf8("allRolesList"))
        self.verticalLayout_5.addWidget(self.allRolesList)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.removeRoleBtn = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeRoleBtn.sizePolicy().hasHeightForWidth())
        self.removeRoleBtn.setSizePolicy(sizePolicy)
        self.removeRoleBtn.setMinimumSize(QtCore.QSize(60, 0))
        self.removeRoleBtn.setObjectName(_fromUtf8("removeRoleBtn"))
        self.verticalLayout_3.addWidget(self.removeRoleBtn)
        self.appendRoleBtn = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appendRoleBtn.sizePolicy().hasHeightForWidth())
        self.appendRoleBtn.setSizePolicy(sizePolicy)
        self.appendRoleBtn.setMinimumSize(QtCore.QSize(60, 0))
        self.appendRoleBtn.setObjectName(_fromUtf8("appendRoleBtn"))
        self.verticalLayout_3.addWidget(self.appendRoleBtn)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.disabledRolesList = QtGui.QListWidget(self.groupBox)
        self.disabledRolesList.setObjectName(_fromUtf8("disabledRolesList"))
        self.verticalLayout_4.addWidget(self.disabledRolesList)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.depNameEdit = QtGui.QLineEdit(self.groupBox)
        self.depNameEdit.setObjectName(_fromUtf8("depNameEdit"))
        self.gridLayout_2.addWidget(self.depNameEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.depSIDEdit = QtGui.QLineEdit(self.groupBox)
        self.depSIDEdit.setObjectName(_fromUtf8("depSIDEdit"))
        self.gridLayout_2.addWidget(self.depSIDEdit, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.depDescriptionEdit = QtGui.QLineEdit(self.groupBox)
        self.depDescriptionEdit.setObjectName(_fromUtf8("depDescriptionEdit"))
        self.gridLayout_2.addWidget(self.depDescriptionEdit, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.applyBtn = QtGui.QPushButton(departments)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.applyBtn.sizePolicy().hasHeightForWidth())
        self.applyBtn.setSizePolicy(sizePolicy)
        self.applyBtn.setMaximumSize(QtCore.QSize(300, 16777215))
        self.applyBtn.setObjectName(_fromUtf8("applyBtn"))
        self.horizontalLayout_5.addWidget(self.applyBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 10)
        self.verticalLayout.setStretch(2, 10)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(departments)
        QtCore.QMetaObject.connectSlotsByName(departments)
        departments.setTabOrder(self.departmentsTree, self.newDepBtn)
        departments.setTabOrder(self.newDepBtn, self.newSubDepBtn)
        departments.setTabOrder(self.newSubDepBtn, self.remDepBtn)
        departments.setTabOrder(self.remDepBtn, self.depNameEdit)
        departments.setTabOrder(self.depNameEdit, self.depSIDEdit)
        departments.setTabOrder(self.depSIDEdit, self.depDescriptionEdit)
        departments.setTabOrder(self.depDescriptionEdit, self.allRolesList)
        departments.setTabOrder(self.allRolesList, self.removeRoleBtn)
        departments.setTabOrder(self.removeRoleBtn, self.appendRoleBtn)
        departments.setTabOrder(self.appendRoleBtn, self.disabledRolesList)
        departments.setTabOrder(self.disabledRolesList, self.applyBtn)

    def retranslateUi(self, departments):
        departments.setWindowTitle(QtGui.QApplication.translate("departments", "Departments management", None, QtGui.QApplication.UnicodeUTF8))
        self.newDepBtn.setText(QtGui.QApplication.translate("departments", "new root department", None, QtGui.QApplication.UnicodeUTF8))
        self.newSubDepBtn.setText(QtGui.QApplication.translate("departments", "append subdepartment", None, QtGui.QApplication.UnicodeUTF8))
        self.remDepBtn.setText(QtGui.QApplication.translate("departments", "remove department", None, QtGui.QApplication.UnicodeUTF8))
        self.departmentsTree.headerItem().setText(0, QtGui.QApplication.translate("departments", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.departmentsTree.headerItem().setText(1, QtGui.QApplication.translate("departments", "SID", None, QtGui.QApplication.UnicodeUTF8))
        self.departmentsTree.headerItem().setText(2, QtGui.QApplication.translate("departments", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("departments", "Department information", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("departments", "All roles", None, QtGui.QApplication.UnicodeUTF8))
        self.removeRoleBtn.setText(QtGui.QApplication.translate("departments", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.appendRoleBtn.setText(QtGui.QApplication.translate("departments", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("departments", "Disabled roles for this department", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("departments", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("departments", "SID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("departments", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.applyBtn.setText(QtGui.QApplication.translate("departments", "Apply", None, QtGui.QApplication.UnicodeUTF8))

